import chromadb
from pathlib import Path

CHROMA_PATH = Path(__file__).resolve().parent / "chroma_store"

career_docs = [
    # --- ROLE BENCHMARKS ---
    {"id": "rb_01", "text": "A Mid-Level Software Engineer (3-5 years) writes clean, testable code and owns features independently. A Senior Engineer (5-8 years) designs systems, mentors juniors, and drives technical decisions across the team. A Staff Engineer (8+ years) sets technical direction across multiple teams, identifies org-wide problems, and influences roadmap without direct authority."},
    {"id": "rb_02", "text": "A Principal Engineer operates at the intersection of business and technology. They translate business goals into engineering strategy, evaluate build-vs-buy decisions, and are accountable for the technical health of an entire product line. They spend 40-60% of time on architecture, design reviews, and cross-team alignment."},
    {"id": "rb_03", "text": "A Solutions Architect bridges the gap between sales/clients and engineering. They design end-to-end technical solutions for client problems, produce architecture diagrams and technical proposals, and ensure the solution is feasible within budget and timeline. Strong communication and cloud expertise are mandatory."},
    {"id": "rb_04", "text": "A Cloud Architect designs and governs cloud infrastructure strategy. They define multi-cloud or hybrid-cloud standards, enforce security and compliance policies, optimize cloud costs, and guide teams on IaC (Terraform, Pulumi). AWS/GCP/Azure certifications (Solutions Architect, Professional level) are the standard benchmark."},
    {"id": "rb_05", "text": "An Engineering Manager (EM) is responsible for people, not code. Their job is hiring, performance reviews, career growth of reports, team morale, and removing blockers. A good EM shields the team from organizational chaos and translates company goals into team-level priorities. They should still understand the codebase but no longer own individual features."},
    {"id": "rb_06", "text": "A Director of Engineering manages multiple teams through Engineering Managers. They own quarterly planning, headcount decisions, cross-team dependencies, and engineering culture. They report to VP Engineering and are expected to think in quarters and years, not sprints."},
    {"id": "rb_07", "text": "A VP of Engineering owns the entire engineering org. Responsibilities include org design, hiring strategy, budget management, executive communication, and aligning engineering output with company OKRs. This role requires strong business acumen in addition to technical credibility."},
    {"id": "rb_08", "text": "A CTO (Chief Technology Officer) in a product company sets the long-term technology vision, evaluates emerging tech, represents engineering externally (investors, press, partners), and partners with the CEO on product strategy. In startups, CTOs often still write code; in large companies they are fully strategic."},
    {"id": "rb_09", "text": "A Product Manager (PM) owns the 'what and why' of a product. They gather user research, define requirements in PRDs, prioritize the backlog, and align engineering + design + business stakeholders. Senior PMs own an entire product area; Directors of Product own a product line with multiple PMs reporting to them."},
    {"id": "rb_10", "text": "A Data Engineering Lead designs and maintains the data platform — pipelines, warehouses, and data quality frameworks. They work with Spark, Airflow, dbt, and cloud warehouses like BigQuery or Snowflake. At senior levels they define the data architecture and set standards for the entire data org."},

    # --- CAREER TRANSITIONS ---
    {"id": "ct_01", "text": "Transitioning from Software Engineer to Engineering Manager: The biggest shift is from personal output to team output. Start by taking on informal leadership — running standups, mentoring a junior, owning a project end-to-end. Read 'The Manager's Path' by Camille Fournier. Expect a 6-12 month adjustment period where you feel less productive because your impact is now indirect."},
    {"id": "ct_02", "text": "Transitioning from Senior Engineer to Staff Engineer: The key unlock is scope. A Senior Engineer owns a service; a Staff Engineer owns a problem across services. Start writing technical proposals (RFCs), proactively identify systemic issues, and build influence across teams without using authority. Will Larson's 'Staff Engineer' book is the definitive guide."},
    {"id": "ct_03", "text": "Transitioning from Backend Engineer to Solutions Architect: Focus on breadth over depth. Learn AWS/Azure/GCP at a professional certification level, practice drawing system architecture diagrams (C4 model), develop client communication skills, and build experience estimating project costs and timelines. The transition typically takes 2-3 years of deliberate effort."},
    {"id": "ct_04", "text": "Transitioning from Software Engineer to Product Manager: You need to shift from 'how to build' to 'what to build and why'. Develop skills in user research (interviews, surveys), data analysis (SQL, Mixpanel, Amplitude), and stakeholder communication. Build a portfolio of product thinking — write teardowns of apps you use. Most successful SWE-to-PM transitions happen internally within a company."},
    {"id": "ct_05", "text": "Transitioning from Data Analyst to Data Engineer: Learn Python at an intermediate level (Pandas, PySpark), master SQL window functions and query optimization, pick up Apache Airflow for pipeline orchestration, and learn one cloud data warehouse deeply (BigQuery or Snowflake). Build 2-3 end-to-end pipelines as portfolio projects. Timeline: 6-12 months of focused learning."},
    {"id": "ct_06", "text": "Transitioning from individual contributor to people manager for senior IT professionals: The hardest part is identity shift — you no longer measure success by code written. Success is now measured by the growth and output of your team. Develop active listening, feedback delivery (SBI model: Situation-Behavior-Impact), and conflict resolution skills. Join management communities like Rands Leadership Slack."},
    {"id": "ct_07", "text": "Transitioning from Engineering Manager back to Individual Contributor (IC): This is more common than people think. Many EMs realize they miss technical work. The key is to stay technically sharp during your management years — do code reviews, attend architecture discussions, write internal tools. When returning to IC, target Staff or Principal roles that leverage your management experience as a superpower."},
    {"id": "ct_08", "text": "Transitioning from on-premise/legacy systems to cloud-native roles: Start with AWS Cloud Practitioner certification (2-4 weeks), then target the Solutions Architect Associate (2-3 months). Learn Docker and Kubernetes fundamentals, understand 12-factor app principles, and rebuild one of your existing projects on a cloud provider. Companies actively seek engineers who can migrate legacy systems."},
    {"id": "ct_09", "text": "Transitioning from software development to DevOps/SRE: Focus on Linux administration, networking fundamentals (DNS, HTTP, load balancers), CI/CD pipelines (GitHub Actions, Jenkins), infrastructure as code (Terraform), container orchestration (Kubernetes), and observability (Prometheus, Grafana, ELK stack). The Google SRE book is free online and is the foundational text."},
    {"id": "ct_10", "text": "Transitioning from technical role to consulting or advisory: Senior IT professionals with 15+ years of experience can move into independent consulting. Build a niche (cloud migration, digital transformation, data strategy), develop a personal brand on LinkedIn, start by consulting for your existing network, and productize your knowledge into frameworks and templates clients pay for."},

    # --- SKILL GAP FRAMEWORKS ---
    {"id": "sg_01", "text": "The core skill gaps between mid-level and senior engineers are: (1) System design — ability to design scalable, fault-tolerant distributed systems. (2) Ambiguity tolerance — working effectively when requirements are unclear. (3) Ownership — proactively identifying and fixing problems without being asked. (4) Communication — writing clear technical docs, RFCs, and presenting to non-technical stakeholders."},
    {"id": "sg_02", "text": "The skill gap between Senior Engineer and Staff Engineer is primarily scope and influence. Senior Engineers are given problems; Staff Engineers find problems. Senior Engineers persuade their team; Staff Engineers build consensus across org boundaries. The technical bar is similar — the difference is organizational impact and the ability to operate with high autonomy."},
    {"id": "sg_03", "text": "Common skill gaps for IT professionals targeting architect roles: (1) Cost awareness — architects must design for budget, not just performance. (2) Security-first thinking — every design decision has a threat surface. (3) Documentation and diagramming — C4 model, sequence diagrams, ADRs (Architecture Decision Records). (4) Vendor evaluation — knowing when to use managed services vs build custom."},
    {"id": "sg_04", "text": "Skill gaps for senior engineers moving into leadership: (1) Giving direct, kind feedback — most engineers are conflict-averse. (2) Delegating without micromanaging. (3) Running 1-on-1s effectively — these are for the report, not the manager. (4) Hiring — writing good job descriptions, structured interview design, avoiding bias. (5) Navigating organizational politics without becoming political."},
    {"id": "sg_05", "text": "Soft skill gaps that hold back senior IT professionals: (1) Executive presence — communicating confidently to C-suite with structured, concise framing. (2) Negotiation — salary, scope, and resource negotiation. (3) Stakeholder management — keeping non-technical stakeholders informed without overwhelming them. (4) Strategic thinking — connecting daily work to company-level goals."},
    {"id": "sg_06", "text": "Technical skills every senior IT professional should have regardless of specialization: Advanced SQL, at least one scripting language (Python or Bash), understanding of distributed systems concepts (CAP theorem, eventual consistency, idempotency), basic security knowledge (OWASP top 10, auth patterns), and cloud fundamentals on at least one major provider."},

    # --- LEADERSHIP FRAMEWORKS ---
    {"id": "lf_01", "text": "The Situational Leadership model by Hersey and Blanchard identifies four leadership styles: Directing (high task, low relationship) for new team members, Coaching (high task, high relationship) for developing members, Supporting (low task, high relationship) for capable but unmotivated members, and Delegating (low task, low relationship) for high performers. Effective leaders adapt their style to each person."},
    {"id": "lf_02", "text": "The SBI Feedback Model (Situation-Behavior-Impact) is the gold standard for giving feedback in engineering teams. Situation: describe the specific context. Behavior: describe the observable action, not the personality. Impact: describe the effect on the team, product, or user. Example: 'In yesterday's design review (S), you interrupted Sarah twice before she finished (B), which made her disengage for the rest of the session (I).'"},
    {"id": "lf_03", "text": "Psychological Safety, defined by Amy Edmondson, is the belief that you will not be punished for speaking up with ideas, questions, concerns, or mistakes. It is the single strongest predictor of high-performing engineering teams according to Google's Project Aristotle. Leaders build it by modeling vulnerability, rewarding dissent, and separating blame from problem-solving in post-mortems."},
    {"id": "lf_04", "text": "The RACI matrix (Responsible, Accountable, Consulted, Informed) is used by senior IT leaders to clarify ownership on complex cross-team projects. Every task has exactly one Accountable person (who owns the outcome), one or more Responsible people (who do the work), Consulted parties (whose input is needed), and Informed parties (who need updates). Ambiguous ownership is the root cause of most project failures."},
    {"id": "lf_05", "text": "OKRs (Objectives and Key Results) are used by senior engineering leaders to align team work with company goals. The Objective is qualitative and inspiring ('Make our platform the most reliable in the industry'). Key Results are quantitative and measurable ('Reduce P1 incidents from 12/month to 3/month by Q3'). Good OKRs are ambitious — hitting 70% is considered success."},
    {"id": "lf_06", "text": "The concept of 'Technical Debt' as a leadership communication tool: senior engineers must be able to explain technical debt in business terms to non-technical leaders. Frame it as risk and opportunity cost: 'Our current auth system will take 3x longer to add SSO than if we refactor it. The refactor costs 2 sprints now but saves 6 sprints over the next year and reduces security risk.'"},
    {"id": "lf_07", "text": "Radical Candor by Kim Scott defines the ideal leadership style as caring personally while challenging directly. The four quadrants: Radical Candor (care + challenge), Ruinous Empathy (care but don't challenge — most common failure mode for new managers), Obnoxious Aggression (challenge but don't care), and Manipulative Insincerity (neither). Most new engineering managers fall into Ruinous Empathy."},
    {"id": "lf_08", "text": "The concept of 'Glue Work' coined by Tanya Reilly describes the invisible work that holds teams together — onboarding new members, writing documentation, improving processes, organizing cross-team sync. Senior engineers and tech leads often do disproportionate glue work. Leaders must make this work visible, valued, and distributed fairly across the team."},

    # --- EQ AND SENIOR PROFESSIONAL DEVELOPMENT ---
    {"id": "eq_01", "text": "Emotional Intelligence (EQ) for senior IT professionals has four components relevant to the workplace: Self-awareness (knowing your triggers and blind spots), Self-regulation (managing reactions under pressure, especially in incidents or heated design debates), Empathy (understanding team members' motivations and frustrations), and Social skills (influencing, inspiring, and resolving conflict)."},
    {"id": "eq_02", "text": "Active listening is a critical skill for senior IT professionals in leadership roles. It means giving full attention, not planning your response while the other person speaks, asking clarifying questions ('What did you mean by X?'), and paraphrasing to confirm understanding ('So what I'm hearing is...'). In 1-on-1s, the manager should speak less than 30% of the time."},
    {"id": "eq_03", "text": "Managing up is an essential skill for senior engineers and tech leads. It means proactively keeping your manager informed, framing problems with proposed solutions (not just complaints), understanding your manager's priorities and pressures, and making their job easier. Senior professionals who manage up effectively get more autonomy, resources, and opportunities."},
    {"id": "eq_04", "text": "Mentoring vs Coaching distinction for senior IT professionals: Mentoring is sharing your experience and giving advice ('Here's what worked for me'). Coaching is asking questions to help someone find their own answers ('What do you think you should do?'). Great tech leads know when to mentor (knowledge gaps) and when to coach (confidence or ownership gaps)."},
    {"id": "eq_05", "text": "Dealing with burnout as a senior IT professional: High performers are most susceptible to burnout because they take on the most. Warning signs: cynicism about work, reduced performance on tasks you used to do easily, physical exhaustion. Prevention: strong work boundaries, regular 1-on-1s with your manager about workload, delegation, and finding meaning in the work beyond just task completion."},

    # --- LEARNING ROADMAPS ---
    {"id": "lr_01", "text": "6-month learning roadmap to become AWS Solutions Architect: Month 1-2: AWS Cloud Practitioner (Foundational). Month 3-4: AWS Solutions Architect Associate (core services: EC2, S3, RDS, VPC, IAM, Lambda, CloudFront). Month 5: Build a full project on AWS (deploy a web app with auto-scaling, RDS backend, CloudFront CDN). Month 6: AWS Solutions Architect Professional or AWS Developer Associate. Use Adrian Cantrill's courses, not just Udemy."},
    {"id": "lr_02", "text": "6-month roadmap for a senior engineer targeting system design interviews at FAANG: Month 1: Read 'Designing Data-Intensive Applications' by Martin Kleppmann (chapters 1-6). Month 2: Study distributed systems patterns (consistent hashing, leader election, saga pattern). Month 3-4: Practice 2 system design problems per week (Grokking System Design). Month 5: Mock interviews with peers. Month 6: Review weak areas, focus on estimation and back-of-envelope calculations."},
    {"id": "lr_03", "text": "Learning roadmap for senior engineers to develop leadership skills over 12 months: Quarter 1: Read 'The Manager's Path' + start running team retrospectives. Quarter 2: Take on a mentee, practice SBI feedback model. Quarter 3: Lead a cross-team project, write your first RFC or technical proposal. Quarter 4: Shadow your manager in hiring panels and quarterly planning. Apply for a tech lead or senior+ role."},
    {"id": "lr_04", "text": "Roadmap for transitioning from a service-based company (TCS, Infosys, Wipro) to a product-based company: Step 1: Rebuild your resume around impact and ownership, not client names. Step 2: Spend 3 months on DSA (LeetCode medium, focus on arrays, trees, graphs, DP). Step 3: Study system design for 2 months. Step 4: Build or contribute to 1-2 open source or personal projects. Step 5: Network on LinkedIn, target companies via referrals. Timeline: 6-12 months."},
    {"id": "lr_05", "text": "Skills roadmap for IT professionals targeting fintech or banking technology roles: Must-haves: strong understanding of ACID transactions, distributed payment systems, regulatory compliance basics (PCI-DSS, GDPR), event-driven architecture (Kafka), and security (encryption at rest and in transit, OAuth2). Nice-to-haves: ISO 20022 messaging standard, core banking system architecture knowledge."},
]

def ingest():
    client = chromadb.PersistentClient(path=str(CHROMA_PATH))
    collection = client.get_or_create_collection(name="career_knowledge")

    existing = collection.get()
    existing_ids = set(existing["ids"])

    new_docs = [d for d in career_docs if d["id"] not in existing_ids]
    if not new_docs:
        print("ChromaDB already up to date.")
        return

    collection.add(
        documents=[d["text"] for d in new_docs],
        ids=[d["id"] for d in new_docs],
    )
    print(f"Ingested {len(new_docs)} documents into ChromaDB.")

if __name__ == "__main__":
    ingest()